// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaTec.Gbso.Dal;

namespace PruebaTec.Gbso.Dal.Migrations
{
    [DbContext(typeof(RootDbContext))]
    [Migration("20210913120555_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PruebaTec.Gbso.Models.TipoIdentificacionModel", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoIdentificacionModel");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "CC"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "RC"
                        },
                        new
                        {
                            Id = (short)3,
                            Name = "TI"
                        },
                        new
                        {
                            Id = (short)4,
                            Name = "CE"
                        },
                        new
                        {
                            Id = (short)5,
                            Name = "PA"
                        });
                });

            modelBuilder.Entity("PruebaTec.Gbso.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasenia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("TipoIdentificacionId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("TipoIdentificacionId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PruebaTec.Gbso.Models.UsuarioModel", b =>
                {
                    b.HasOne("PruebaTec.Gbso.Models.TipoIdentificacionModel", "TipoIdentificacion")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoIdentificacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoIdentificacion");
                });

            modelBuilder.Entity("PruebaTec.Gbso.Models.TipoIdentificacionModel", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
